baseURL: "https://japrietov.github.io/" 
title: Jeisson Prieto
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2 
        - name: Resume
          url: CV_2025.pdf
          weight: 3


params:
    description: "This website hosts Jeisson Prieto's research papers, curriculum vitae, and contact information."
    author: Jeisson Prieto
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jeisson Prieto
          subtitle: "I’m a PhD student in Applied Economics & Management at Cornell University. My research lies at the intersection of climate change, international trade, and water resources. Before starting my PhD, I completed a Master’s in Applied Mathematics and a Bachelor’s in Computer and Systems Engineering at the Universidad Nacional de Colombia."
          imageUrl: "jp2276_squared.png"
          imageWidth: 160"
          imageHeight: 160"
          buttons:
            - name: Papers
              url: papers/
            - name: Talks
              url: talks/
            - name: Resume
              url: CV_2025.pdf
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
              # url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        # - name: CV
        #   url: CV_2025.pdf
        - name: Email
          url: mailto:jp2276@cornell.edu
        - name: Location
          url: location/
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=5hGcelEAAAAJ
        - name: GitHub
          url: https://github.com/japrietov
        - name: LinkedIn
          url: https://www.linkedin.com/in/jeisson-prieto/
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jeisson Prieto"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2